[package]
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
description = "libdav1d bindings"
edition = "2021"
keywords = ["dav1d-rs","av1"]
license = "MIT"
name = "dav1d"
readme = "README.md"
repository = "https://github.com/rust-av/dav1d-rs"
version = "0.7.0"

[dependencies]
dav1d-sys = { version = "0.4.0", path = "dav1d-sys" }

[workspace]
members = ["dav1d-sys", "tools"]
