[package]
name = "dav1d-sys"
version = "0.3.1"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "FFI bindings to dav1d"
repository = "https://github.com/rust-av/dav1d-rs"
edition = "2018"

build = "build.rs"

[features]
build = []

[package.metadata.pkg-config]
dav1d = "0.2.0"

[build-dependencies]
bindgen = "0.53.1"
metadeps = "1.1.2"

[dependencies]
