[package]
name = "dav1d-sys"
version = "0.1.1"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "FFI bindings to dav1d"
repository = "https://github.com/rust-av/dav1d-rs"

build = "build.rs"

[package.metadata.pkg-config]
dav1d = "0.1.0"

[build-dependencies]
bindgen = "0.45.0"
metadeps = "1.1.2"
pkg-config = "0.3.12"

[dependencies]
