[package]
name = "dav1d-tools"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
edition = "2018"

[dependencies]
dav1d = { path = "..", version = "0.10" }
bitstream-io = "3.2"
log = "0.4"
structopt = "0.3"
