[package]
name = "dav1d-tools"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
edition = "2018"

[dependencies]
dav1d = { path = "..", version = "0.2.0" }
bitstream-io = "0.8"
log = "0.4"
structopt = "0.2"
